# Generated by Django 2.2.24 on 2021-10-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='wahtch_date',
            new_name='watch_date',
        ),
    ]
